### ISSUE TITLE
Demo App is signed

### ISSUE THREAD

**Issue by ns-1m** [mweisman/ShapeKit#1]
Demo App is signed by the developer.

ERROR

Code Sign error: The identity 'iPhone Developer' doesn't match any valid certificate/private key pair in the default keychain

**Comment by mweisman** [comment]
Code signing settings have been set to Don't Sign in the sample app. For more on using your own signing profile, see the [iOS Provisioning Portal](https://developer.apple.com/ios/manage/overview/index.action) (link requires a paid iOS developer account).

[Commit 214fc6e2beaba3c588ea4ec17ab2d112180142df](https://github.com/mweisman/ShapeKit/commit/214fc6e2beaba3c588ea4ec17ab2d112180142df)
